name: demo
services:
  secret-sidecar:
    image: secret-sidecar:dev
    secrets:
      - op_token
    environment:
      # Choose one:
      OP_SERVICE_ACCOUNT_TOKEN_FILE: /run/secrets/op_token
      #OP_SERVICE_ACCOUNT_TOKEN: $OP_SERVICE_ACCOUNT_TOKEN
      secret_TEST_SECRET: "op://Testing/SecretPassword/password"
    command: --log-level=debug --provider=op
    volumes:
      - ./secrets/templates:/templates:ro
      - secrets-store:/run/secrets
  demo:
    image: busybox
    user: "65532:65532"
    command: ["cat", "/run/secrets/test_secret"]
    depends_on:
      secret-sidecar:
        condition: service_healthy
    volumes:
      - secrets-store:/run/secrets
secrets:
  op_token:
    file: /home/bbradley/.op/service_account_token
volumes:
  secrets-store:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs

