services:
  secret-sidecar:
    build: .
    image: ghcr.io/bpbradley/secret-sidecar:latest
    user: "65532:65532"
    environment:
      # Choose one:
      # OP_SERVICE_ACCOUNT_TOKEN_FILE: /path/to/file
      OP_SERVICE_ACCOUNT_TOKEN: $OP_SERVICE_ACCOUNT_TOKEN
      secret_DB_PASSWORD: "op://Prod DB/Postgres/password"
    volumes:
      - ./secrets/templates:/templates:ro
      - secrets-store:/run/secrets
      - sidecar-status:/status
  demo:
    image: busybox
    user: "65532:65532"
    command: ["sh", "-c", "sleep 3600"]
    depends_on:
      secret-sidecar:
        condition: service_healthy
    volumes:
      - secrets-store:/run/secrets:ro

volumes:
  secrets-store:
  sidecar-status:
