---
name: demo
services:
  secret-sidecar:
    image: ghcr.io/bpbradley/secret-sidecar:op
    secrets:
      - op_token
    environment:
      OP_SERVICE_ACCOUNT_TOKEN_FILE: /run/secrets/op_token
      secret_TEST_SECRET: "op://Testing/SecretPassword/password"
    command: --log-level=debug
    volumes:
      - ./secrets/templates:/templates:ro
      - secrets-store:/run/secrets
  demo:
    image: busybox
    user: "65532:65532"
    command: ["cat", "/run/secrets/test_secret"]
    depends_on:
      secret-sidecar:
        condition: service_healthy
    volumes:
      - secrets-store:/run/secrets
secrets:
  op_token:
    file: ~/.op/service_account_token
volumes:
  secrets-store:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
