---
name: demo
services:
  locket:
    user: "1000:1000" #default is 65532:65532 if not provided
    image: ghcr.io/bpbradley/locket:op
    secrets:
      - op_token
    environment:
      OP_SERVICE_ACCOUNT_TOKEN_FILE: /run/secrets/op_token
      secret_TEST_SECRET: "op://Mordin/SecretPassword/password"
    command:
      - "--log-level=debug"
    volumes:
      - ./secrets/templates:/templates:ro
      - secrets-store:/run/secrets
  demo:
    image: busybox
    user: "1000:1000"
    command: ["cat", "/run/secrets/test_secret"]
    depends_on:
      locket:
        condition: service_healthy
    volumes:
      - secrets-store:/run/secrets
secrets:
  op_token:
    file: /etc/op/token
volumes:
  secrets-store:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: uid=1000,gid=1000,mode=700